### ISSUE TITLE
This Project dead?

### ISSUE THREAD

**Issue by phi-whiterabbit** [quantego/clp-java#17]
Hi. May i kindly ask whether this project is dead?
The Most recent clp stable version is 1.17.6 while this one seems to be for Version 1.16.11 and no release has been made in more than one year.

**Comment by loehndorf** [comment]
CLP is a very mature product so is this interface. Is there a tangible benefit of rolling to the next version?

**Comment by loehndorf** [comment]
Oh... and "no". The project is not dead ;)

**Comment by phi-whiterabbit** [comment]
Maybe i misunderstood. I was under the impression that this interface has to be used with the exakt same version of clp, thus 1.16.11. Is this wrong?
If this understanding is true, then a reason to switch to a newer clp would be the bugs that have been fixed since 1.16.11.

**Comment by loehndorf** [comment]
CLP comes packaged with 1.16. Feel free to build you own by packaging 1.17 and putting it in the corresponding directory under resources. It's always a bit of work to compile for all platforms, so that I only do it when I really see a benefit. My next plan is to add ARM support for the new Macs and AWS instances.

**Comment by loehndorf** [comment]
The project is not dead.
